// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mprjgwlxusyadifdtyce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcmpnd2x4dXN5YWRpZmR0eWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODkzNDUsImV4cCI6MjA2NTA2NTM0NX0.5-n8UZPyp0EogZUbKtxVMzlQffzDw_fFyhgAQEG9o3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);